import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from '../components/navbar'

const inter = Inter({ subsets: ["latin"] });

const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

console.log('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:', clerkPublishableKey);
console.log('CLERK_SECRET_KEY:', process.env.CLERK_SECRET_KEY);


export const metadata = {
  title: "DevLiftoff",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include meta tags, title, and other head elements here */}
        <link rel="icon" href="/dev_icon.png" />
      </head>
      <body className={inter.className}>
        <ClerkProvider>
          <NavBar />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
