import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from '../components/navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DevLiftoff",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include meta tags, title, and other head elements here */}
      </head>
      <body className={inter.className}>
        <ClerkProvider>
          <NavBar />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
